og_login = 'your_login'
og_password = 'your_password'
og_domain = 'fr'
og_universe = '10'
og_id_mother_planet = '1234567'
og_planets = {'340001', '340002', '340003'} #every planets except the target one
og_main_planet_coordonates = ['1', '300', '6']
og_metal_threshold = 1000000
og_large_cargo_to_send = '100'
mobile_number = '0607080910'
default_message = 'Hello Alex. Your empire is under attack. Log in as soon as possible!'
message_file = '/tmp/message'
call_file = '/tmp/ogame_attack_warning.call'
asterisk_outgoing = '/var/spool/asterisk/outgoing/'
